### ISSUE TITLE
Add continuous integration docs

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/docs.opencivicdata.org#1]
Once you have a working scraper, you need a way to run it regularly and monitor its status. Could you add some docs on your Jenkins setup (or whatever else)?

**Comment by jamesturk** [comment]
This is a good idea, will do once we get the basics taken care of.

**Comment by jamesturk** [comment]
we've started using a hosted service (provided free to Open Source projects) called Bamboo- Jenkins was becoming a maintenance nightmare

this is possibly a better subject for a blog post than inclusion in the documentation- I'm not sure there's yet a good solution for this task that's best for everyone, if we had time I think we'd write up our own but CI tools work decently for this

**Comment by jpmckinney** [comment]
Cool, you can schedule daily builds with Bamboo? A blog post would be fine, yeah.

**Comment by jpmckinney** [comment]
Was a blog post written about this?

**Comment by jamesturk** [comment]
oops- no, didn't mean to close.

**Comment by jpmckinney** [comment]
I think this may mainly involve improving moxie's docs, so closing here.
