### ISSUE TITLE
openvicivdata.org domain expired and pointing to potentially malicious spam site

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/docs.opencivicdata.org#110]
The domain for `opencivicdata.org` has expired and now redirects to a spam site that is potentially malicious:

![Screen Shot 2021-07-25 at 10 09 15 AM](https://user-images.githubusercontent.com/919583/126903968-370d1f2a-30eb-4ff8-ba62-a5b280534887.png)

Unless someone in the Open Civic Data community purchases the domain from the new owner, all links to `opencivicdata.org` should be updated to point to https://opencivicdata.readthedocs.io/en/latest/

The following links are impacted:

* docs.opencivicdata.org
* api.opencivicdata.org
* opencivicdata.org

As of writing this issue, there are about 130 references throughout github that point to one or more of the above links: https://github.com/search?q=opencivicdata.org&type=code

Related to #107

**Comment by hancush** [comment]
I put the root docs up on RTD: https://opencivicdata-docs.readthedocs.io/en/latest/

https://opencivicdata.readthedocs.io/en/latest/ is instructions for customizing WhatsApp ringtones.

**Comment by hancush** [comment]
Docs now accessible at https://opencivicdata.info

**Comment by kstohr** [comment]
Hey guys looks like this domain has expired again...
