### ISSUE TITLE
event OCDEP is missing things

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/docs.opencivicdata.org#27]
Event.{description, location, classification} to name a few, probably more?  need to look at it closer

also cc @paultag in case he knows what's up

**Comment by paultag** [comment]
Location is in there, but not mentioned as a key explicitly. The others might have fell through. I thought I hit them all. Let me sweep over it again.

**Comment by jamesturk** [comment]
@paultag did this get updated?

**Comment by paultag** [comment]
Yeah, we had two bugs open, looks like - https://github.com/opencivicdata/docs.opencivicdata.org/pull/29 - good to close?

**Comment by jamesturk** [comment]
Sure
