### ISSUE TITLE
Person level participation data in events

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/docs.opencivicdata.org#37]
In Chicago we have individual level participation in events (which aldermen went to what council meeting or committee meeting). @paultag asked me to open up an issue for extending the Events OCDPEP for this data.

**Comment by fgregg** [comment]
Since all the existing proposals have already been accepted, should I create a new proposal? @jamesturk @paultag

**Comment by fgregg** [comment]
Reading the events proposal, it looks like the model suggested should allow for this? No?

**Comment by jpmckinney** [comment]
Indeed - Looks to me like this is what an `Event`'s `participants` already enables.
