### ISSUE TITLE
seems like page numbering is 1-indexed?

### ISSUE THREAD

**Issue by boblannon** [opencivicdata/docs.opencivicdata.org#39]
https://github.com/opencivicdata/docs.opencivicdata.org/blob/master/api/overview.rst#common-parameters

says that the range for `page` is (0 - max_page), but that's evidently not true?

https://api.opencivicdata.org/jurisdictions/?apikey=xxxx&page=0

response:

```
{
"error": "No such page (heh, literally - its out of bounds)"
}
```

**Comment by mileswwatkins** [comment]
Pages are indeed `1`-indexed for now! We'll fix this after the docsprints.
