### ISSUE TITLE
Update to docs?

### ISSUE THREAD

**Issue by mheadd** [opencivicdata/docs.opencivicdata.org#52]
The docs currently have a note on them:

```
 Parts of Open Civic Data underwent a large refactor as of mid-2014, some information on this page may be out of date. 
 We’re working on updating this documentation as soon as possible.
```

Has the documentation been update yet? If not, any thoughts on when they might be?

**Comment by rshorey** [comment]
Scraper-writing documentation has been updated (and the warnings removed).

**Comment by ErnieAtLYD** [comment]
Hey there - looks like I'm still seeing the warning on this page: http://docs.opencivicdata.org/en/latest/

**Comment by rshorey** [comment]
I'm not 100% confident we updated all documentation - I know I did scraper-writing (and the warnings are gone there) as of July 2015. But I didn't touch OCD formats, for example.

**Comment by jpmckinney** [comment]
Dup #32
