### ISSUE TITLE
OCDEP 5: given_name and family_name were added

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/docs.opencivicdata.org#53]
http://docs.opencivicdata.org/en/latest/proposals/0005.html

In this PR: https://github.com/opencivicdata/python-opencivicdata-django/pull/26

**Comment by fgregg** [comment]
So what are we supposed to do with these kind of changes? 

I approve these being added, btw.

**Comment by jpmckinney** [comment]
I don't know the OCDEP process, but we either need to update 0005 or create a new OCDEP to document the change.

**Comment by fgregg** [comment]
I don't know the process either, @jamesturk @paultag ?

**Comment by jamesturk** [comment]
Usually this would be a new OCDEP.  Given the sort of transitory nature of things I'd be fine just amending OCDEP5 this time though as they've been in there a while so in a sense not including them was just an oversight.
