### ISSUE TITLE
Person/Organization image field source/note

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/docs.opencivicdata.org#54]
The image field on Person and Organization models are only for a URL string. It seems metadata attributing credit or name of the source for the photo (GPO Member Guide) and a possible note (e.g. "Official Congress Headshot") would provide more complete information about the photo.

via @crdunwel https://github.com/opencivicdata/python-opencivicdata-django/issues/41

**Comment by jpmckinney** [comment]
I suppose we could have these sources added under `sources`? Otherwise we might end up having sources for individual properties all over the place.

**Comment by jamesturk** [comment]
that seems right to me

**Comment by jpmckinney** [comment]
If using the existing `sources` is the way to go, then there is no need to change the OCDEP.

**Comment by fgregg** [comment]
Right now a source field provides two fields, `note` and `url`. Since the person and organization images fields are already urls, is the thinking that we should duplicate the image url into the source url?
