### ISSUE TITLE
Improve naming of Bill#from_organization field

### ISSUE THREAD

**Issue by patcon** [opencivicdata/docs.opencivicdata.org#58]
(Creating this as a placeholder for revisiting during a major revision.)

Related Slack conversation: https://opencivicdata.slack.com/archives/pupa/p1454452385000025

On my reading, `from_organization` struck me as the organization (in my case, a committee) from which the Bill originated. The actual intention is that it represents the parent legislature organization. My thought is that this should probably be reflected in a better name, perhaps `from_legislature`.

cc: @fgregg

**Comment by jpmckinney** [comment]
In the legislative systems that OpenCivicData originally targeted, `from_organization` is indeed the organization in which the bill was introduced. In state/provincial/federal legislatures, bills are introduced in lower or upper house, then discussed in committees. The things you're tracking aren't really 'bills', so the model doesn't work perfectly for your use cases and require workarounds.

**Comment by jpmckinney** [comment]
I don't think the confusion is so severe as to justify breaking backwards-compatibility, but I can re-open if there's disagreement on that.
