### ISSUE TITLE
Campaign Finance Filing: Review attribute updates

### ISSUE THREAD

**Issue by jpmckinney** [opencivicdata/docs.opencivicdata.org#68]
It's not clear that `CommitteeStatusUpdate` can't be rolled into `CommitteeAttributeUpdate` - just add `description` to `CommitteeAttributeUpdate`.

Also, the class name already establishes the semantics, so I'd change `attribute_to_update` to `property` and `new_attribute_value` to `value`.

**Comment by jpmckinney** [comment]
Ping @aepton

**Comment by aepton** [comment]
Oh my god, sorry, I knew I was procrastinating but yeesh. Especially since I nagged y'all about approving my proposal ;) Sorry sorry! Just submitted a PR that fixes this and addresses some of the issues in the other...issue as well.
