### ISSUE TITLE
Update action types in documentation

### ISSUE THREAD

**Issue by jamesturk** [opencivicdata/docs.opencivicdata.org#70]
action types on https://opencivicdata.readthedocs.io/en/latest/scrape/bills.html no longer match  https://github.com/opencivicdata/python-opencivicdata-django/blob/b720b72e3ee919444131e9d188ef6ba4ca3e9fab/opencivicdata/common.py

**Comment by jpmckinney** [comment]
Maybe just link to https://github.com/opencivicdata/python-opencivicdata-django/blob/b720b72e3ee919444131e9d188ef6ba4ca3e9fab/opencivicdata/common.py#L74-L97 ?

We can also add some comments to the file to orient people to use the first item in the tuple.
