### ISSUE TITLE
Campaign Finance Filing: "person" <> contributor

### ISSUE THREAD

**Issue by jsfenfen** [opencivicdata/docs.opencivicdata.org#72]
I don't think I get the logic of making contributors "persons"--is this an optional designation? 

@aepton, @jpmckinney : Consider the case of a committee giving to another committee. Wouldn't that mean the committee is a committee (and hence a subtype of a popolo org) when it is *receiving* money and other times the committee is a person (and then a subtype of a popolo person) when it is *donating*? To my nose that doesn't smell right and makes tracking the flow of money harder, not easier.

Moreover, differentiating contributor types is often the *point* of this sorta work, even if there aren't easy answers available in the source data. Being able to say that XX percent of funds came from corporate donors is pretty powerful... I don't really understand the rules here, but I'd make donor type it's own field, where person and organization are options, but only assigned if there's solid reason for thinking this (in many jurisdictions this info can be gleaned, at least in part, though I'm sure that's not true everywhere). And, of course, detailed local knowledge may be the only way to know for sure...

**Comment by aepton** [comment]
Yeah, that's a good point. Committee -> Committee breaks the notion of sender == person and recipient == person.

What would be a good entity type here? Post or Organization could conceivably fit, but not without a bit of leakiness in the abstraction.

It could be a Transaction Entity, with optional Person and Organization fields, either of which is filled out depending on what the sender/recipient are.

**Comment by jpmckinney** [comment]
I think we can model this similar to how [Bill models sponsorships](http://docs.opencivicdata.org/en/latest/proposals/0006.html), which allows both people and organizations to sponsor bills.

**Comment by aepton** [comment]
Fixed.

**Comment by jpmckinney** [comment]
Closed by #71
