### ISSUE TITLE
Server returning 500 error as text

### ISSUE THREAD

**Issue by jasonab** [opencivicdata/docs.opencivicdata.org#9]
The /people endpoint is returning a 500 error this morning, but it appears the HTTP status code is 200, while the text says "<h1>Server Error (500)</h1>".

All errors should be returned as an HTTP status code so clients will act correctly.

**Comment by jamesturk** [comment]
Can you provide the request that you're getting this error on?

**Comment by jasonab** [comment]
Sorry, this is a dupe of https://github.com/opencivicdata/api.opencivicdata.org/issues/5

**Comment by jasonab** [comment]
Also, I was wrong about the status code - bug on my end.
