### ISSUE TITLE
Is the Elections proposal ready to be accepted

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/docs.opencivicdata.org#95]
Now that, California Civic Data Alliance has published data with the election models, so that the models have gotten a good shake down, are we ready to accept the Election PEP?

@jamesturk @jpmckinney @gordonje @palewire?

**Comment by jamesturk** [comment]
👍 I'm good w/ it if others are.

**Comment by jpmckinney** [comment]
👍 (unless there were outstanding issues to resolve, but I don't remember any)

**Comment by palewire** [comment]
:+1:

**Comment by gordonje** [comment]
👍 👍 👍 👍

**Comment by jamesturk** [comment]
if someone wants to take a quick look to sanity check this, I think it is ready to go in the linked PR #100 

decided to space these out a bit and accept this as OCDEP20 (taking some influence from how PEP/DEPs have done so to keep related proposals somewhat close together)
